services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: mysql-agendatel
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports: 
      - '3308:3306'
    networks: 
      - agenda-network
    volumes:
      - mysql-agenda:/var/lib/mysql  

networks:
  agenda-network:
    driver: bridge

volumes:
  mysql-agenda:
